name: Run API Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Выберите версию Node.js, которая вам нужна

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run path/to/your/collection.json -e path/to/your/environment.json
